# Generated by Django 5.1.7 on 2025-03-31 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_chaicertificate_chaireview_chaistore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaistore',
            old_name='chai_varities',
            new_name='chai_varieties',
        ),
    ]
